blank_issues_enabled: true
contact_links:
  - name: TorchMeter Community Support
    url: https://github.com/TorchMeter/torchmeter/discussions
    about: Please ask and answer questions here.
  
  - name: TorchMeter Documentation
    url: https://torchmeter.github.io/docs/vers/latest
    about: Please check the documentation here.
